<?php

session_start();

if(!isset($_SESSION['language'])){
	define('lg',0);
} else {
	define('lg',$_SESSION['language']);
}

	// Sintaxe = $local_oque = array('Portugues','Ingles','Espanhol');

	// HOME --------------------

	// Banner da Home


    // CONTATO ------------------

		// campos

		// coluna direita

 	// RODAPE --------------------

	// MENU ----------------------

	// MENU LINKS ----------------------

// ------------------------------------------------/
?>